// Comprehensive database of HEC-recognized universities in Pakistan
// Public + private sector universities and degree-awarding institutions, with campuses.
// Compiled from HEC (Higher Education Commission, Pakistan) recognized-university records.
// Total entries: 256
// Note: HEC periodically adds/renames universities and issues NOC suspensions for some
// private institutes — always cross-check against hec.gov.pk before relying on this for admissions decisions.

export const universities = [
  { name: "National University of Sciences and Technology (NUST)", code: "nust", campuses: ["Main Campus (Islamabad)", "CEME (Rawalpindi)", "MCS (Rawalpindi)", "SNSAT (Islamabad)", "NBS (Islamabad)"] },
  { name: "FAST-NUCES", code: "fast", campuses: ["Islamabad", "Lahore", "Karachi", "Peshawar", "Chiniot-Faisalabad"] },
  { name: "Lahore University of Management Sciences (LUMS)", code: "lums", campuses: ["Main Campus (Lahore)"] },
  { name: "COMSATS University Islamabad (CUI)", code: "comsats", campuses: ["Islamabad", "Lahore", "Abbottabad", "Vehari", "Wah", "Attock", "Sahiwal"] },
  { name: "University of Engineering and Technology (UET)", code: "uet", campuses: ["Lahore (Main)", "Taxila", "Peshawar", "New Campus (Lahore)"] },
  { name: "Air University", code: "air", campuses: ["Islamabad (Main)", "Multan", "Karachi", "Kamra"] },
  { name: "GIKI (Ghulam Ishaq Khan Institute)", code: "giki", campuses: ["Topi (Main)"] },
  { name: "University of the Punjab", code: "pu", campuses: ["Quaid-e-Azam Campus (Lahore)"] },
  { name: "University of Karachi", code: "uok", campuses: ["Main Campus"] },
  { name: "IBA Karachi", code: "iba", campuses: ["Main Campus (Karachi)", "Sukkur", "Larkana"] },
  { name: "Bahria University", code: "bahria", campuses: ["Islamabad", "Karachi", "Lahore"] },
  { name: "HITEC University", code: "hitec", campuses: ["Taxila"] },
  { name: "Usman Institute of Technology (UIT)", code: "uit", campuses: ["Karachi"] },
  { name: "Sir Syed University of Engineering and Technology (SSUET)", code: "ssuet", campuses: ["Karachi"] },
  { name: "Riphah International University", code: "riphah-international-university", campuses: ["Islamabad (Main)", "Rawalpindi", "Faisalabad", "Lahore", "Malakand"] },
  { name: "Capital University of Science & Technology", code: "capital-university-of-science-and-technology", campuses: ["Main Campus (Islamabad)"] },
  { name: "Quaid-i-Azam University", code: "quaid-i-azam-university", campuses: ["Main Campus (Islamabad)"] },
  { name: "Pakistan Institute of Engineering and Applied Sciences (PIEAS)", code: "pakistan-institute-of-engineering-and-applied-sciences", campuses: ["Main Campus (Nilore, Islamabad)"] },
  { name: "National Defence University", code: "national-defence-university", campuses: ["Main Campus (Islamabad)"] },
  { name: "Allama Iqbal Open University", code: "allama-iqbal-open-university", campuses: ["Main Campus (Islamabad)"] },
  { name: "International Islamic University, Islamabad", code: "international-islamic-university-islamabad", campuses: ["Main Campus (Islamabad)"] },
  { name: "National University of Modern Languages (NUML)", code: "national-university-of-modern-languages", campuses: ["Islamabad (Main)", "Rawalpindi", "Faisalabad", "Lahore", "Multan", "Karachi", "Hyderabad", "Peshawar", "Quetta", "Gujranwala"] },
  { name: "Sir Syed CASE Institute of Technology", code: "sir-syed-case-institute-of-technology", campuses: ["Main Campus (Islamabad)"] },
  { name: "Federal Urdu University of Arts, Science and Technology", code: "federal-urdu-university-of-arts-science-and-technology", campuses: ["Islamabad (Main)", "Karachi"] },
  { name: "Institute of Space Technology", code: "institute-of-space-technology", campuses: ["Main Campus (Islamabad)"] },
  { name: "Foundation University, Islamabad", code: "foundation-university-islamabad", campuses: ["Islamabad (Main)", "Rawalpindi", "Sialkot"] },
  { name: "Virtual University of Pakistan", code: "virtual-university-of-pakistan", campuses: ["Lahore (Main)", "Virtual campuses nationwide"] },
  { name: "Shifa Tameer-e-Millat University", code: "shifa-tameer-e-millat-university", campuses: ["Main Campus (Islamabad)"] },
  { name: "Shaheed Zulfiqar Ali Bhutto Medical University", code: "shaheed-zulfiqar-ali-bhutto-medical-university", campuses: ["Main Campus (Islamabad)"] },
  { name: "Muslim Youth University", code: "muslim-youth-university", campuses: ["Main Campus (Islamabad)"] },
  { name: "National University of Technology (NUTECH)", code: "national-university-of-technology", campuses: ["Main Campus (Islamabad)"] },
  { name: "Pakistan Institute of Development Economics (PIDE)", code: "pakistan-institute-of-development-economics", campuses: ["Main Campus (Islamabad)"] },
  { name: "National Skills University", code: "national-skills-university", campuses: ["Main Campus (Islamabad)"] },
  { name: "IBADAT International University Islamabad", code: "ibadat-international-university-islamabad", campuses: ["Main Campus (Islamabad)"] },
  { name: "University of Balochistan", code: "university-of-balochistan", campuses: ["Quetta (Main)", "Mastung", "Kharan", "Pishin"] },
  { name: "Bolan University of Medical & Health Sciences", code: "bolan-university-of-medical-and-health-sciences", campuses: ["Main Campus (Quetta)"] },
  { name: "Al-Hamd Islamic University", code: "al-hamd-islamic-university", campuses: ["Main Campus (Islamabad)"] },
  { name: "Balochistan University of Information Technology, Engineering and Management Sciences (BUITEMS)", code: "balochistan-university-of-information-technology-engineering-and-management-sciences", campuses: ["Quetta (Main)", "Zhob"] },
  { name: "Sardar Bahadur Khan Women's University", code: "sardar-bahadur-khan-women-s-university", campuses: ["Quetta (Main)", "Noshki", "Pishin"] },
  { name: "University of Turbat", code: "university-of-turbat", campuses: ["Main Campus (Turbat)"] },
  { name: "University of Gwadar", code: "university-of-gwadar", campuses: ["Main Campus (Gwadar)"] },
  { name: "University of Makran", code: "university-of-makran", campuses: ["Main Campus (Panjgur)"] },
  { name: "Balochistan University of Engineering and Technology", code: "balochistan-university-of-engineering-and-technology", campuses: ["Main Campus (Khuzdar)"] },
  { name: "Lasbela University of Agriculture, Water and Marine Sciences", code: "lasbela-university-of-agriculture-water-and-marine-sciences", campuses: ["Uthal, Lasbela (Main)", "Wadh", "Dera Murad Jamali"] },
  { name: "University of Loralai", code: "university-of-loralai", campuses: ["Main Campus (Loralai)"] },
  { name: "Mir Chakar Khan Rind University", code: "mir-chakar-khan-rind-university", campuses: ["Main Campus (Sibi)"] },
  { name: "Islamia College University", code: "islamia-college-university", campuses: ["Main Campus (Peshawar)"] },
  { name: "University of Peshawar", code: "university-of-peshawar", campuses: ["Main Campus (Peshawar)"] },
  { name: "University of Agriculture, Peshawar", code: "university-of-agriculture-peshawar", campuses: ["Peshawar (Main)", "Mardan"] },
  { name: "CECOS University of IT and Emerging Sciences", code: "cecos-university-of-it-and-emerging-sciences", campuses: ["Main Campus (Peshawar)"] },
  { name: "University of Engineering and Technology, Peshawar", code: "university-of-engineering-and-technology-peshawar", campuses: ["Peshawar (Main)", "Abbottabad", "Bannu", "Jalozai", "Kohat"] },
  { name: "Gandhara University", code: "gandhara-university", campuses: ["Main Campus (Peshawar)"] },
  { name: "Institute of Management Sciences, Peshawar", code: "institute-of-management-sciences-peshawar", campuses: ["Main Campus (Peshawar)"] },
  { name: "IQRA National University", code: "iqra-national-university", campuses: ["Peshawar (Main)", "Swat"] },
  { name: "Qurtuba University", code: "qurtuba-university", campuses: ["Peshawar (Main)", "Dera Ismail Khan"] },
  { name: "Sarhad University of Science and IT", code: "sarhad-university-of-science-and-it", campuses: ["Peshawar (Main)", "Mardan"] },
  { name: "City University of Science and IT, Peshawar", code: "city-university-of-science-and-it-peshawar", campuses: ["Main Campus (Peshawar)"] },
  { name: "Shaheed Benazir Bhutto Women University", code: "shaheed-benazir-bhutto-women-university", campuses: ["Main Campus (Peshawar)"] },
  { name: "Khyber Medical University", code: "khyber-medical-university", campuses: ["Peshawar (Main)", "Abbottabad", "Bannu", "Dera Ismail Khan", "Saidu Sharif"] },
  { name: "Abasyn University", code: "abasyn-university", campuses: ["Peshawar (Main)", "Islamabad"] },
  { name: "University of Agriculture, Dera Ismail Khan", code: "university-of-agriculture-dera-ismail-khan", campuses: ["Main Campus (Dera Ismail Khan)"] },
  { name: "Gomal University", code: "gomal-university", campuses: ["Dera Ismail Khan (Main)", "Tank"] },
  { name: "Abbottabad University of Science and Technology", code: "abbottabad-university-of-science-and-technology", campuses: ["Main Campus (Havelian, Abbottabad)"] },
  { name: "Kohat University of Science and Technology", code: "kohat-university-of-science-and-technology", campuses: ["Kohat (Main)", "Hangu"] },
  { name: "Women University Swabi", code: "women-university-swabi", campuses: ["Main Campus (Swabi)"] },
  { name: "University of Swabi", code: "university-of-swabi", campuses: ["Main Campus (Swabi)"] },
  { name: "University of Swat", code: "university-of-swat", campuses: ["Main Campus (Swat)"] },
  { name: "University of Engineering & Applied Sciences, Swat", code: "university-of-engineering-and-applied-sciences-swat", campuses: ["Main Campus (Swat)"] },
  { name: "University of Veterinary & Animal Sciences KP", code: "university-of-veterinary-and-animal-sciences-kp", campuses: ["Main Campus (Charsadda)"] },
  { name: "University of Haripur", code: "university-of-haripur", campuses: ["Main Campus (Haripur)"] },
  { name: "Pak-Austria Fachhochschule Institute of Applied Sciences and Technology", code: "pak-austria-fachhochschule-institute-of-applied-sciences-and-technology", campuses: ["Main Campus (Haripur)"] },
  { name: "University of Engineering and Technology, Mardan", code: "university-of-engineering-and-technology-mardan", campuses: ["Main Campus (Mardan)"] },
  { name: "Women University Mardan", code: "women-university-mardan", campuses: ["Main Campus (Mardan)"] },
  { name: "Abdul Wali Khan University Mardan", code: "abdul-wali-khan-university-mardan", campuses: ["Mardan (Main)", "Chitral", "Pabbi"] },
  { name: "Hazara University", code: "hazara-university", campuses: ["Mansehra (Main)", "Battagram"] },
  { name: "Northern University, Nowshera", code: "northern-university-nowshera", campuses: ["Main Campus (Nowshera)"] },
  { name: "University of Science and Technology Bannu", code: "university-of-science-and-technology-bannu", campuses: ["Main Campus (Bannu)"] },
  { name: "Shaheed Benazir Bhutto University, Sheringal", code: "shaheed-benazir-bhutto-university-sheringal", campuses: ["Upper Dir (Main)", "Chitral"] },
  { name: "University of Malakand", code: "university-of-malakand", campuses: ["Main Campus (Chakdara)"] },
  { name: "University of Buner", code: "university-of-buner", campuses: ["Main Campus (Buner)"] },
  { name: "University of Technology, Nowshera", code: "university-of-technology-nowshera", campuses: ["Main Campus (Nowshera)"] },
  { name: "FATA University", code: "fata-university", campuses: ["Main Campus (Akhorwal, Kohat)"] },
  { name: "University of Chitral", code: "university-of-chitral", campuses: ["Main Campus (Chitral)"] },
  { name: "University of Lakki Marwat", code: "university-of-lakki-marwat", campuses: ["Main Campus (Lakki Marwat)"] },
  { name: "Khushal Khan Khattak University", code: "khushal-khan-khattak-university", campuses: ["Main Campus (Karak)"] },
  { name: "Bacha Khan University", code: "bacha-khan-university", campuses: ["Main Campus (Charsadda)"] },
  { name: "University of Dir", code: "university-of-dir", campuses: ["Main Campus (Timergara)"] },
  { name: "University of Shangla", code: "university-of-shangla", campuses: ["Main Campus (Shangla)"] },
  { name: "King Edward Medical University", code: "king-edward-medical-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Forman Christian College University", code: "forman-christian-college-university", campuses: ["Main Campus (Lahore)"] },
  { name: "National College of Arts", code: "national-college-of-arts", campuses: ["Lahore (Main)", "Rawalpindi"] },
  { name: "University of Veterinary and Animal Sciences (UVAS)", code: "university-of-veterinary-and-animal-sciences", campuses: ["Lahore (Main)", "Jhang", "Pattoki", "Narowal", "Layyah"] },
  { name: "Punjab Tianjin University of Technology", code: "punjab-tianjin-university-of-technology", campuses: ["Main Campus (Lahore)"] },
  { name: "Kinnaird College for Women University", code: "kinnaird-college-for-women-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Government College University, Lahore (GCU)", code: "government-college-university-lahore", campuses: ["Main Campus (Lahore)"] },
  { name: "Lahore College for Women University", code: "lahore-college-for-women-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Fatima Jinnah Medical University", code: "fatima-jinnah-medical-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Institute of Management Sciences, Lahore", code: "institute-of-management-sciences-lahore", campuses: ["Main Campus (Lahore)"] },
  { name: "University of Management and Technology, Lahore (UMT)", code: "university-of-management-and-technology-lahore", campuses: ["Lahore (Main)", "Sialkot"] },
  { name: "National College of Business Administration and Economics (NCBA&E)", code: "national-college-of-business-administration-and-economics", campuses: ["Lahore (Main)", "Multan", "Bahawalpur", "Rahim Yar Khan"] },
  { name: "University of Central Punjab (UCP)", code: "university-of-central-punjab", campuses: ["Main Campus (Lahore)"] },
  { name: "University of Health Sciences, Lahore", code: "university-of-health-sciences-lahore", campuses: ["Main Campus (Lahore)"] },
  { name: "University of Education, Lahore", code: "university-of-education-lahore", campuses: ["Lahore (Main)", "Attock", "Dera Ghazi Khan", "Faisalabad", "Jauharabad", "Multan", "Vehari"] },
  { name: "University of Lahore (UOL)", code: "university-of-lahore", campuses: ["Lahore (Main)", "Sargodha"] },
  { name: "Beaconhouse National University", code: "beaconhouse-national-university", campuses: ["Main Campus (Lahore)"] },
  { name: "University of South Asia", code: "university-of-south-asia", campuses: ["Main Campus (Lahore)"] },
  { name: "Superior University", code: "superior-university", campuses: ["Lahore (Main)", "Okara", "Sargodha", "Rahim Yar Khan", "Faisalabad"] },
  { name: "Minhaj University, Lahore", code: "minhaj-university-lahore", campuses: ["Main Campus (Lahore)"] },
  { name: "Pakistan Institute of Fashion and Design (PIFD)", code: "pakistan-institute-of-fashion-and-design", campuses: ["Main Campus (Lahore)"] },
  { name: "Information Technology University of the Punjab (ITU)", code: "information-technology-university-of-the-punjab", campuses: ["Main Campus (Lahore)"] },
  { name: "Lahore School of Economics", code: "lahore-school-of-economics", campuses: ["Main Campus (Lahore)"] },
  { name: "University of Home Economics Lahore", code: "university-of-home-economics-lahore", campuses: ["Main Campus (Lahore)"] },
  { name: "NUR International University", code: "nur-international-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Qarshi University", code: "qarshi-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Hajvery University", code: "hajvery-university", campuses: ["Lahore (Main)", "Sheikhupura"] },
  { name: "Institute for Art and Culture", code: "institute-for-art-and-culture", campuses: ["Main Campus (Lahore)"] },
  { name: "Green International University", code: "green-international-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Lahore Institute of Science and Technology", code: "lahore-institute-of-science-and-technology", campuses: ["Main Campus (Lahore)"] },
  { name: "Rashid Latif Khan University", code: "rashid-latif-khan-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Lahore Garrison University", code: "lahore-garrison-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Ali Institute of Education", code: "ali-institute-of-education", campuses: ["Main Campus (Lahore)"] },
  { name: "Imperial College of Business Studies", code: "imperial-college-of-business-studies", campuses: ["Main Campus (Lahore)"] },
  { name: "Lahore Leads University", code: "lahore-leads-university", campuses: ["Main Campus (Lahore)"] },
  { name: "Lahore University of Biological and Applied Sciences", code: "lahore-university-of-biological-and-applied-sciences", campuses: ["Main Campus (Lahore)"] },
  { name: "University of Child Health Sciences", code: "university-of-child-health-sciences", campuses: ["Main Campus (Lahore)"] },
  { name: "National University of Pakistan", code: "national-university-of-pakistan", campuses: ["Main Campus (Rawalpindi)"] },
  { name: "Pir Mehr Ali Shah Arid Agriculture University", code: "pir-mehr-ali-shah-arid-agriculture-university", campuses: ["Main Campus (Rawalpindi)"] },
  { name: "Fatima Jinnah Women University", code: "fatima-jinnah-women-university", campuses: ["Main Campus (Rawalpindi)"] },
  { name: "Rawalpindi Medical University", code: "rawalpindi-medical-university", campuses: ["Main Campus (Rawalpindi)"] },
  { name: "National University of Medical Sciences", code: "national-university-of-medical-sciences", campuses: ["Main Campus (Rawalpindi)"] },
  { name: "Rawalpindi Women University", code: "rawalpindi-women-university", campuses: ["Main Campus (Rawalpindi)"] },
  { name: "Government Viqar-un-Nisa Women University", code: "government-viqar-un-nisa-women-university", campuses: ["Main Campus (Rawalpindi)"] },
  { name: "University of Agriculture, Faisalabad", code: "university-of-agriculture-faisalabad", campuses: ["Faisalabad (Main)", "Burewala", "Toba Tek Singh", "Depalpur"] },
  { name: "Government College University, Faisalabad", code: "government-college-university-faisalabad", campuses: ["Faisalabad (Main)", "Layyah", "Sahiwal", "Chiniot"] },
  { name: "National Textile University", code: "national-textile-university", campuses: ["Faisalabad (Main)", "Karachi"] },
  { name: "Faisalabad Medical University", code: "faisalabad-medical-university", campuses: ["Main Campus (Faisalabad)"] },
  { name: "The University of Faisalabad", code: "the-university-of-faisalabad", campuses: ["Main Campus (Faisalabad)"] },
  { name: "Government College Women University, Faisalabad", code: "government-college-women-university-faisalabad", campuses: ["Main Campus (Faisalabad)"] },
  { name: "Government Sadiq College Women University", code: "government-sadiq-college-women-university", campuses: ["Main Campus (Bahawalpur)"] },
  { name: "The Islamia University of Bahawalpur", code: "the-islamia-university-of-bahawalpur", campuses: ["Bahawalpur (Main)", "Bahawalnagar", "Rahim Yar Khan"] },
  { name: "Cholistan University of Veterinary and Animal Sciences", code: "cholistan-university-of-veterinary-and-animal-sciences", campuses: ["Main Campus (Bahawalpur)"] },
  { name: "University of Wah", code: "university-of-wah", campuses: ["Main Campus (Wah Cantt)"] },
  { name: "University of Sargodha", code: "university-of-sargodha", campuses: ["Main Campus (Sargodha)"] },
  { name: "Al-Karam International Institute", code: "al-karam-international-institute", campuses: ["Main Campus (Bhera)"] },
  { name: "GIFT University", code: "gift-university", campuses: ["Main Campus (Gujranwala)"] },
  { name: "International Institute of Science, Arts and Technology", code: "international-institute-of-science-arts-and-technology", campuses: ["Main Campus (Gujranwala)"] },
  { name: "The University of Chenab", code: "the-university-of-chenab", campuses: ["Main Campus (Gujrat)"] },
  { name: "University of Gujrat", code: "university-of-gujrat", campuses: ["Gujrat (Main)", "Lahore", "Rawalpindi", "Mandi Bahauddin"] },
  { name: "Government College Women University, Sialkot", code: "government-college-women-university-sialkot", campuses: ["Main Campus (Sialkot)"] },
  { name: "University of Sialkot", code: "university-of-sialkot", campuses: ["Main Campus (Sialkot)"] },
  { name: "Grand Asian University Sialkot", code: "grand-asian-university-sialkot", campuses: ["Main Campus (Sialkot)"] },
  { name: "NFC Institute of Engineering and Technology", code: "nfc-institute-of-engineering-and-technology", campuses: ["Main Campus (Multan)"] },
  { name: "Bahauddin Zakariya University", code: "bahauddin-zakariya-university", campuses: ["Multan (Main)", "Layyah", "Vehari"] },
  { name: "Women University Multan", code: "women-university-multan", campuses: ["Main Campus (Multan)"] },
  { name: "University of Southern Punjab", code: "university-of-southern-punjab", campuses: ["Main Campus (Multan)"] },
  { name: "Muhammad Nawaz Sharif University of Agriculture", code: "muhammad-nawaz-sharif-university-of-agriculture", campuses: ["Main Campus (Multan)"] },
  { name: "Muhammad Nawaz Sharif University of Engineering and Technology", code: "muhammad-nawaz-sharif-university-of-engineering-and-technology", campuses: ["Main Campus (Multan)"] },
  { name: "Multan University of Science & Technology", code: "multan-university-of-science-and-technology", campuses: ["Main Campus (Multan)"] },
  { name: "Times Institute", code: "times-institute", campuses: ["Main Campus (Multan)"] },
  { name: "Nishtar Medical University", code: "nishtar-medical-university", campuses: ["Main Campus (Multan)"] },
  { name: "Emerson University, Multan", code: "emerson-university-multan", campuses: ["Main Campus (Multan)"] },
  { name: "Khawaja Fareed University of Engineering and Information Technology", code: "khawaja-fareed-university-of-engineering-and-information-technology", campuses: ["Main Campus (Rahim Yar Khan)"] },
  { name: "Punjab University of Technology, Rasul", code: "punjab-university-of-technology-rasul", campuses: ["Main Campus (Mandi Bahauddin)"] },
  { name: "University of Sahiwal", code: "university-of-sahiwal", campuses: ["Main Campus (Sahiwal)"] },
  { name: "University of Okara", code: "university-of-okara", campuses: ["Main Campus (Okara)"] },
  { name: "University of Jhang", code: "university-of-jhang", campuses: ["Main Campus (Jhang)"] },
  { name: "Ghazi University", code: "ghazi-university", campuses: ["Main Campus (Dera Ghazi Khan)"] },
  { name: "Mir Chakar Khan Rind University of Technology", code: "mir-chakar-khan-rind-university-of-technology", campuses: ["Main Campus (Dera Ghazi Khan)"] },
  { name: "Ghazi National Institute of Engineering & Sciences", code: "ghazi-national-institute-of-engineering-and-sciences", campuses: ["Main Campus (Dera Ghazi Khan)"] },
  { name: "University of Narowal", code: "university-of-narowal", campuses: ["Main Campus (Narowal)"] },
  { name: "Al-Qadir University", code: "al-qadir-university", campuses: ["Main Campus (Sohawa)"] },
  { name: "Baba Guru Nanak University", code: "baba-guru-nanak-university", campuses: ["Main Campus (Nankana Sahib)"] },
  { name: "University of Chakwal", code: "university-of-chakwal", campuses: ["Main Campus (Chakwal)"] },
  { name: "University of Mianwali", code: "university-of-mianwali", campuses: ["Main Campus (Mianwali)"] },
  { name: "Namal University", code: "namal-university", campuses: ["Main Campus (Mianwali)"] },
  { name: "Thal University", code: "thal-university", campuses: ["Main Campus (Bhakkar)"] },
  { name: "Kohsar University Murree", code: "kohsar-university-murree", campuses: ["Main Campus (Murree)"] },
  { name: "Institute of Management & Applied Sciences", code: "institute-of-management-and-applied-sciences", campuses: ["Main Campus (Khanewal)"] },
  { name: "University of Layyah", code: "university-of-layyah", campuses: ["Main Campus (Layyah)"] },
  { name: "KASB Institute of Technology", code: "kasb-institute-of-technology", campuses: ["Main Campus (Karachi)"] },
  { name: "Sindh Madressatul Islam University", code: "sindh-madressatul-islam-university", campuses: ["Main Campus (Karachi)"] },
  { name: "NED University of Engineering and Technology", code: "ned-university-of-engineering-and-technology", campuses: ["Karachi (Main)", "Tharparkar"] },
  { name: "Dow University of Health Sciences", code: "dow-university-of-health-sciences", campuses: ["Main Campus (Karachi)"] },
  { name: "Dawood University of Engineering and Technology", code: "dawood-university-of-engineering-and-technology", campuses: ["Main Campus (Karachi)"] },
  { name: "Pakistan Naval Academy", code: "pakistan-naval-academy", campuses: ["Main Campus (Karachi)"] },
  { name: "Indus Valley School of Art and Architecture", code: "indus-valley-school-of-art-and-architecture", campuses: ["Main Campus (Karachi)"] },
  { name: "Baqai Medical University", code: "baqai-medical-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Hamdard University", code: "hamdard-university", campuses: ["Karachi (Main)", "Islamabad"] },
  { name: "Textile Institute of Pakistan", code: "textile-institute-of-pakistan", campuses: ["Main Campus (Karachi)"] },
  { name: "Institute of Business Management (IoBM)", code: "institute-of-business-management", campuses: ["Main Campus (Karachi)"] },
  { name: "Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology (SZABIST)", code: "shaheed-zulfiqar-ali-bhutto-institute-of-science-and-technology", campuses: ["Karachi (Main)", "Hyderabad", "Islamabad", "Larkana", "Gharo"] },
  { name: "Karachi Institute of Economics and Technology (KIET)", code: "karachi-institute-of-economics-and-technology", campuses: ["Main Campus (Karachi)"] },
  { name: "Greenwich University, Karachi", code: "greenwich-university-karachi", campuses: ["Main Campus (Karachi)"] },
  { name: "Jinnah University for Women", code: "jinnah-university-for-women", campuses: ["Main Campus (Karachi)"] },
  { name: "Iqra University", code: "iqra-university", campuses: ["Karachi (Main)", "Islamabad", "Quetta"] },
  { name: "Dadabhoy Institute of Higher Education", code: "dadabhoy-institute-of-higher-education", campuses: ["Main Campus (Karachi)"] },
  { name: "Ilma University", code: "ilma-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Preston University", code: "preston-university", campuses: ["Karachi (Main)", "Islamabad", "Lahore", "Peshawar"] },
  { name: "Indus University", code: "indus-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Aga Khan University", code: "aga-khan-university", campuses: ["Karachi (Main)", "London"] },
  { name: "Muhammad Ali Jinnah University", code: "muhammad-ali-jinnah-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Sindh Institute of Medical Sciences", code: "sindh-institute-of-medical-sciences", campuses: ["Main Campus (Karachi)"] },
  { name: "Karachi School for Business and Leadership", code: "karachi-school-for-business-and-leadership", campuses: ["Main Campus (Karachi)"] },
  { name: "Habib University", code: "habib-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Benazir Bhutto Shaheed University, Lyari", code: "benazir-bhutto-shaheed-university-lyari", campuses: ["Main Campus (Karachi)"] },
  { name: "Jinnah Sindh Medical University", code: "jinnah-sindh-medical-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Shaheed Zulfiqar Ali Bhutto University of Law", code: "shaheed-zulfiqar-ali-bhutto-university-of-law", campuses: ["Main Campus (Karachi)"] },
  { name: "DHA Suffa University", code: "dha-suffa-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Nazeer Hussain University", code: "nazeer-hussain-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Newports Institute of Communications and Economics", code: "newports-institute-of-communications-and-economics", campuses: ["Main Campus (Karachi)"] },
  { name: "Shaheed Benazir Bhutto City University", code: "shaheed-benazir-bhutto-city-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Shaheed Benazir Bhutto Dewan University", code: "shaheed-benazir-bhutto-dewan-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Qalandar Shahbaz University of Modern Sciences", code: "qalandar-shahbaz-university-of-modern-sciences", campuses: ["Main Campus (Karachi)"] },
  { name: "Ziauddin University", code: "ziauddin-university", campuses: ["Karachi (Main)", "Sukkur"] },
  { name: "Salim Habib University", code: "salim-habib-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Sohail University", code: "sohail-university", campuses: ["Main Campus (Karachi)"] },
  { name: "Millennium Institute of Technology and Entrepreneurship", code: "millennium-institute-of-technology-and-entrepreneurship", campuses: ["Main Campus (Karachi)"] },
  { name: "City University of Health Sciences", code: "city-university-of-health-sciences", campuses: ["Main Campus (Karachi)"] },
  { name: "Karachi Institute of Technology & Entrepreneurship", code: "karachi-institute-of-technology-and-entrepreneurship", campuses: ["Main Campus (Karachi)"] },
  { name: "Emaan Institute of Management and Sciences", code: "emaan-institute-of-management-and-sciences", campuses: ["Main Campus (Karachi)"] },
  { name: "Malir University of Science and Technology", code: "malir-university-of-science-and-technology", campuses: ["Main Campus (Karachi)"] },
  { name: "Karachi Institute of Power Engineering (KINPOE)", code: "karachi-institute-of-power-engineering", campuses: ["Main Campus (Karachi)"] },
  { name: "University of Art and Culture, Jamshoro", code: "university-of-art-and-culture-jamshoro", campuses: ["Main Campus (Jamshoro)"] },
  { name: "Shaheed Allah Bux Soomro University of Art, Design and Heritages", code: "shaheed-allah-bux-soomro-university-of-art-design-and-heritages", campuses: ["Main Campus (Jamshoro)"] },
  { name: "Liaquat University of Medical and Health Sciences", code: "liaquat-university-of-medical-and-health-sciences", campuses: ["Jamshoro (Main)", "Thatta"] },
  { name: "University of Sindh", code: "university-of-sindh", campuses: ["Jamshoro (Main)", "Badin", "Dadu", "Mirpur Khas", "Naushahro Feroze", "Thatta"] },
  { name: "Mehran University of Engineering and Technology", code: "mehran-university-of-engineering-and-technology", campuses: ["Jamshoro (Main)", "Khairpur", "Sujawal", "Jacobabad", "Umerkot"] },
  { name: "Shaheed Benazir Bhutto University, Benazirabad", code: "shaheed-benazir-bhutto-university-benazirabad", campuses: ["Benazirabad (Main)", "Sanghar", "Naushehro Feroze"] },
  { name: "Quaid-e-Awam University of Engineering, Science and Technology", code: "quaid-e-awam-university-of-engineering-science-and-technology", campuses: ["Nawabshah (Main)", "Larkana", "Jacobabad"] },
  { name: "Peoples University of Medical and Health Sciences for Women", code: "peoples-university-of-medical-and-health-sciences-for-women", campuses: ["Main Campus (Nawabshah)"] },
  { name: "Shaheed Benazir Bhutto University of Veterinary and Animal Sciences", code: "shaheed-benazir-bhutto-university-of-veterinary-and-animal-sciences", campuses: ["Main Campus (Sakrand)"] },
  { name: "Isra University", code: "isra-university", campuses: ["Hyderabad (Main)", "Islamabad", "Karachi"] },
  { name: "University of EAST", code: "university-of-east", campuses: ["Main Campus (Hyderabad)"] },
  { name: "Hyderabad Institute for Technical & Management Sciences", code: "hyderabad-institute-for-technical-and-management-sciences", campuses: ["Main Campus (Hyderabad)"] },
  { name: "Government College University Hyderabad", code: "government-college-university-hyderabad", campuses: ["Main Campus (Hyderabad)"] },
  { name: "Sukkur IBA University", code: "sukkur-iba-university", campuses: ["Sukkur (Main)", "Hyderabad", "Larkana", "Mirpurkhas", "Kandhkot"] },
  { name: "Aror University of Art, Architecture, Design & Heritage", code: "aror-university-of-art-architecture-design-and-heritage", campuses: ["Main Campus (Sukkur)"] },
  { name: "Begum Nusrat Bhutto Women University", code: "begum-nusrat-bhutto-women-university", campuses: ["Main Campus (Sukkur)"] },
  { name: "Shah Abdul Latif University", code: "shah-abdul-latif-university", campuses: ["Khairpur (Main)", "Ghotki", "Shahdadkot"] },
  { name: "Pir Abdul Qadir Shah Jeelani Institute of Medical Sciences", code: "pir-abdul-qadir-shah-jeelani-institute-of-medical-sciences", campuses: ["Main Campus (Gambat)"] },
  { name: "Benazir Bhutto Shaheed University of Technology and Skill Development", code: "benazir-bhutto-shaheed-university-of-technology-and-skill-development", campuses: ["Main Campus (Khairpur)"] },
  { name: "Shaheed Mohtarma Benazir Bhutto Medical University", code: "shaheed-mohtarma-benazir-bhutto-medical-university", campuses: ["Main Campus (Larkana)"] },
  { name: "University of Larkano", code: "university-of-larkano", campuses: ["Main Campus (Larkana)"] },
  { name: "Sindh Agriculture University", code: "sindh-agriculture-university", campuses: ["Tandojam (Main)", "Khairpur", "Umerkot"] },
  { name: "University of Sufism and Modern Sciences", code: "university-of-sufism-and-modern-sciences", campuses: ["Main Campus (Bhit Shah)"] },
  { name: "Shaikh Ayaz University", code: "shaikh-ayaz-university", campuses: ["Main Campus (Shikarpur)"] },
  { name: "University of Mirpurkhas", code: "university-of-mirpurkhas", campuses: ["Main Campus (Mirpurkhas)"] },
  { name: "Mirpur University of Science and Technology", code: "mirpur-university-of-science-and-technology", campuses: ["Mirpur (AJK) (Main)", "Bhimber"] },
  { name: "University of Azad Jammu and Kashmir", code: "university-of-azad-jammu-and-kashmir", campuses: ["Muzaffarabad (Main)", "Neelam Valley", "Jhelum Valley"] },
  { name: "University of Poonch", code: "university-of-poonch", campuses: ["Rawalakot (Main)", "Sudhanoti", "Haveli"] },
  { name: "Al-Khair University", code: "al-khair-university", campuses: ["Main Campus (Mirpur (AJK))"] },
  { name: "Mohi-ud-Din Islamic University", code: "mohi-ud-din-islamic-university", campuses: ["Main Campus (Nerian Sharif)"] },
  { name: "Women University of Azad Jammu and Kashmir, Bagh", code: "women-university-of-azad-jammu-and-kashmir-bagh", campuses: ["Main Campus (Bagh)"] },
  { name: "University of Kotli", code: "university-of-kotli", campuses: ["Main Campus (Kotli)"] },
  { name: "Karakoram International University", code: "karakoram-international-university", campuses: ["Gilgit (Main)", "Hunza Valley", "Ghizar", "Chilas"] },
  { name: "Baltistan University", code: "baltistan-university", campuses: ["Main Campus (Skardu)"] },
];